### ISSUE TITLE
Alembic autogenerate fails with alembic_version table not found

### ISSUE THREAD

**Issue by ms32035** [snowflakedb/snowflake-sqlalchemy#122]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.7

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

3. What are the component versions in the environment (`pip list`)? 
alembic                    1.2.1
SQLAlchemy                 1.3.10
snowflake-sqlalchemy       1.1.15

4. What did you do?
autogenerate alembic revision with something like:
```
$ alembic revision --autogenerate -m Tables
```
The snowflake URL for sqlalchemy was defined as `snowflake://{user}:{password}@{account}/{dbname}` without schema specified, which might be related, as down the call stack we have observed empty schema for alembic_version table, instead of what was provided by alembic configuration.

5. What did you expect to see?

Correctly generated alembic revision

6. What did you see instead?
Error as per log attached.

7. Can you set logging to DEBUG and collect the logs?

[alembic_trace.txt](https://github.com/snowflakedb/snowflake-sqlalchemy/files/3751397/alebmic_trace.txt)

**Comment by smtakeda** [comment]
Without specifying a schema along with db, no schema is set to the session, so it cannot find the  table.
```
002003 (42S02): SQL compilation error:
Table 'ALEMBIC_VERSION' does not exist.
[SQL: DESCRIBE TABLE /* sqlalchemy:get_primary_keys */ ALEMBIC_VERSION]
```

**Comment by ms32035** [comment]
alembic has as a setting `alembic_table_schema` and this is ignored https://alembic.sqlalchemy.org/en/latest/api/runtime.html?highlight=compare_server_default
