### ISSUE TITLE
network_timeout and login_timeout are not respected

### ISSUE THREAD

**Issue by mike-seekwell** [snowflakedb/snowflake-sqlalchemy#125]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
NA
3. What are the component versions in the environment (`pip list`)? 

Flask-SQLAlchemy==2.2
SQLAlchemy==1.1.14
asn1crypto==0.24.0
snowflake-sqlalchemy==1.1.0

4. What did you do?

         connect_timeout=10
         additionalParams = {'account': snowAccount,
                            'database': s['database'],
                            'warehouse': warehouse,
                            'network_timeout': connect_timeout,
                            'login_timeout': connect_timeout,
                            }
        schema = s.get('db_details', {}).get('schema', False)
        if schema:
            additionalParams['schema'] = schema
        snow_url = sqlalchemy.engine.url.URL("snowflake", 
                           username=s['username'], 
                           password=password,
                           host=snowHost,
                           query=additionalParams)
        db = create_engine(snow_url, connect_args={'connect_timeout': connect_timeout})

5. What did you expect to see?
When putting the wrong accountName (e.g. test12345), I expected `create_engine` to timeout after 10 seconds.
6. What did you see instead?
`create_engine` did not timeout, it took ~2 minutes to return an error
`(snowflake.connector.errors.ForbiddenError) 250001 (08001): Failed to connect to DB. Verify the account name is correct: test12345.us-east-1.snowflakecomputing.com:443. HTTP 403: Forbidden`

**Comment by snowstakeda** [comment]
what is the version of snowflake-connector?

**Comment by yakshup** [comment]
Any updates on this?

**Comment by sfc-gh-dszmolka** [comment]
as part of reviewing old issues, I'm now closing this one.

if this is still an issue in the recent versions (1.5.1), please do comment and we can look further.
