### ISSUE TITLE
Authentication Token Expired (390114) - Any solution for snowflake-sqlalchemy?

### ISSUE THREAD

**Issue by klkpratik** [snowflakedb/snowflake-sqlalchemy#128]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows2012ServerR2 6.3.9600-SP0

3. What are the component versions in the environment (`pip list`)? 
flask
SQLAlchemy
snowflake-connector-python

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

from sqlalchemy import create_engine
engine = create_engine('snowflake://<connection-string>' )
connection = engine.connect()
names = connection.execute_query("select names from employees")

def sensor():
    """ Function for scheduling purposes. """
    v = cursor.execute("""select 1""")
    v = v.fetchall()
    print(v)

sched = BackgroundScheduler(daemon=True)
sched.add_job(sensor,'interval',minutes=50)
sched.start()

5. What did you expect to see?
Expected connection to persist

6. What did you see instead?
Authentication Token expired and connection was lost

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by notkriswagner** [comment]
@klkpratik Try setting `client_session_keep_alive=True` as one of the connection parameters in your create_engine() function call

**Comment by klkpratik** [comment]
@notkriswagner got this error -

TypeError: Invalid argument(s) 'client_session_keep_alive' sent to create_engine(), using configuration SnowflakeDialect/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by klkpratik** [comment]
@notkriswagner I added this parameter in the create_engine() call but still the connection got dropped after 4 hours.

**Comment by klkpratik** [comment]
@smtakeda That is what I exactly tried

**Comment by delijati** [comment]
Any update on this. Should we do an good old `restart server` after 3:59

**Comment by snowstakeda** [comment]
Verified the client session keep alive option worked.
```
engine = create_engine(
...
, connect_args = {'client_session_keep_alive': True})
```

From the given source code, I changed:
```
names = connection.execute_query("select names from employees")
```
to
```
names = connection.execute("select names from employees")
```
and removed the background job.

**Comment by delijati** [comment]
Jup `client_session_keep_alive` also works for me ... but keep in mind you have to call `engine.dispose` (sqlalchemy) or the thread in my case `gitlabci` will hang forever.

**Comment by eyalyoli** [comment]
does `client_session_keep_alive` mean that you get a "forever" token? I don't like this, is there any option to refresh the token manually?
