### ISSUE TITLE
Import of SnowflakeOCSPAsn1Crypto crashes Python

### ISSUE THREAD

**Issue by ms32035** [snowflakedb/snowflake-sqlalchemy#130]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Python 3.7.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Darwin-19.0.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 

see attached log file

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

`from snowflake.connector.ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP` 

see attached log file for the complete process

5. What did you expect to see?

6. What did you see instead?

Python process crashes

7. Can you set logging to DEBUG and collect the logs?
[log.txt](https://github.com/snowflakedb/snowflake-sqlalchemy/files/3837132/log.txt)

**Comment by ms32035** [comment]
My mistake, this should actually go to https://github.com/snowflakedb/snowflake-connector-python

**Comment by smtakeda** [comment]
ok, I can reproduce it:
```
>>> from snowflake.connector.ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP
/private/tmp/tst/sft/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecRandomDefault' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/private/tmp/tst/sft/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/private/tmp/tst/sft/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingPKCS7Key' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/private/tmp/tst/sft/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingPKCS5Key' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/private/tmp/tst/sft/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingPKCS1Key' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
/private/tmp/tst/sft/lib/python3.7/site-packages/cffi/cparser.py:164: UserWarning: Global variable 'kSecPaddingOAEPKey' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')
  "(usually 'extern')" % (decl.name,))
```

**Comment by smtakeda** [comment]
Looks like this started happening from `cffi==1.13.1`

**Comment by ms32035** [comment]
quite possible, I tested downgrading that one version back and it didn't help. Does it completely terminate python for you?
```

**Comment by snowstakeda** [comment]
No, it continues running. Those look like warnings. In my case, downgrading cffi to 1.13.0 removed the warnings.
```
pip install -U cffi==1.13.0
```

**Comment by smtakeda** [comment]
This reproduces it:
```
from oscrypto import asymmetric
```

**Comment by smtakeda** [comment]
Filed https://github.com/wbond/oscrypto/issues/34

**Comment by smtakeda** [comment]
Warning doesn't stop the program.
We'll suppress the warning anyway.

**Comment by ms32035** [comment]
ok, will investigate if downgrade of the package helps for me tomorrow

**Comment by ms32035** [comment]
ok, the warning was just covering up the actual problem. Traced the issue to be caused by this https://forums.developer.apple.com/thread/119429

**Comment by smtakeda** [comment]
Interesting. Sounds like Catalna issue. We'll keep eyes on it.

**Comment by akshjain83** [comment]
@smtakeda @ms32035 How would someone possible go about disabling this warnings? This log messages are eating up too much of the log stream in my apps. Thanks in advance.

**Comment by aydumoulin** [comment]
@smtakeda this issue surfaced again with Big Sur beta

Stack is the following
- python 3.7.6
- Darwin-20.0.0-x86_64-i386-64bit
- openssl 1.1
- cffi 1.13.2
- snowflake-connector-python==2.2.9

Same means of reproducibility as @ms32035 experienced

Also results in 

```
~/.pyenv/versions/3.7.6/lib/python3.7/site-packages/oscrypto/_mac/_security_cffi.py in <module>
    237 security_path = find_library('Security')
    238 if not security_path:
--> 239     raise LibraryNotFoundError('The library Security could not be found')
    240
    241 Security = ffi.dlopen(security_path)

LibraryNotFoundError: The library Security could not be found
```

This fails locally
```bash
python -c 'from ctypes.util import find_library; assert find_library("c")'
```

But will work in 
```bash
docker run 3.7-slim-stretch python -c 'from ctypes.util import find_library; assert find_library("c")'
```

**Comment by asheik16** [comment]
This works thanks a ton 😃  @aydumoulin
