### ISSUE TITLE
Turning SSL on

### ISSUE THREAD

**Issue by kkwan-tc** [snowflakedb/snowflake-sqlalchemy#134]
Python Version 3.6.5
Darwin-18.7.0-x86_64-i386-64bit

Relevant package versions:
snowflake-connector-python 2.0.4
snowflake-sqlalchemy       1.1.16
SQLAlchemy                 1.3.5

I'm having trouble finding this in the documentation
when creating an engine is SSL turned on by default? If not is this the correct way to turn it on? (is it supported?)

```
engine = create_engine(URL(
    account=<>,
    user=<>,
    warehouse=<>,
    role=<>,
    database=<>,
    ),
    connect_args={
        'private_key': pkb,
        'ssl':True}
    )
```

Thanks!

**Comment by smtakeda** [comment]
SSL is always enabled, and there is non-SSL endpoint in the production environment.

**Comment by kkwan-tc** [comment]
Thanks @smtakeda, could you explain what you mean by there is non-SSL endpoint in the prod env? I'm understanding that to be that if we explicitly turn off SSL we would still be able to connect?
Is this correct?
 Thanks in advance.

**Comment by smtakeda** [comment]
@kkwan-tc no, there is no non-SSL option available.

**Comment by kkwan-tc** [comment]
Awesome, thank you!
