### ISSUE TITLE
`_get_schema_columns` broken in release v1.1.17

### ISSUE THREAD

**Issue by dylan-murray** [snowflakedb/snowflake-sqlalchemy#142]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

`3.7`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

`Ubuntu`

3. What are the component versions in the environment (`pip list`)? 

```
snowflake-connector-python 2.1.1
snowflake-sqlalchemy       1.1.17
SQLAlchemy                 1.3.11
```

4. What did you do?

Issue is breaking code that was previously working in v1.1.16

6. What did you see instead?

```
sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 252004: Binding parameters must be a list: {'table_schema': ''}

[SQL:
        SELECT /* sqlalchemy:_get_columns_in_schema */
               ic.table_name,
               ic.column_name,
               ic.data_type,
               ic.character_maximum_length,
               ic.numeric_precision,
               ic.numeric_scale,
               ic.is_nullable,
               ic.column_default,
               ic.is_identity,
               ic.comment
          FROM information_schema.columns ic
         WHERE ic.table_schema=%(table_schema)s
         ORDER BY ic.ordinal_position]
parameters: {'table_schema': ''}]
(Background on this error at: http://sqlalche.me/e/f405)
```

seems to be occurring here https://github.com/snowflakedb/snowflake-sqlalchemy/blob/db3104d0fcd076700bc68648a892e80cc4c0214a/snowdialect.py#L325-L339

**Comment by rhlahuja** [comment]
We likely need a `snowflake.connector.paramstyle = u'pyformat'` before the `result = connection.execute(...)`.


This works:
```python
import snowflake.connector
from snowflake.sqlalchemy.snowdialect import SnowflakeDialect

snowflake.connector.paramstyle = u'pyformat'
print(SnowflakeDialect().get_columns(db.engine, 'test_table', schema='test_schema'))
```
however, this doesn't:
```python
snowflake.connector.paramstyle = u'qmark'
print(SnowflakeDialect().get_columns(db.engine, 'test_table', schema='test_schema'))
```

**Comment by biagaspar** [comment]
Is there an update on this? I have the same error but on my case I can't change the paramstyle from `snowflake.connector.paramstyle = u'qmark'` to `snowflake.connector.paramstyle = u'pyformat'` as I need to use `qmark` to bypass the Issue: `maximum number of expressions in a list exceeded, expected at most 16,384`. 
This other Issue and solution suggestion can be seen here: [https://github.com/snowflakedb/snowflake-connector-python/issues/37]

**Comment by keller00** [comment]
This issue was resolved, I just forgot to close it here. @biagaspar could you open a new issue with your problem?
