### ISSUE TITLE
Install from source breaks python interpreter

### ISSUE THREAD

**Issue by anujkumar93** [snowflakedb/snowflake-sqlalchemy#146]
1. What version of Python are you using (`python --version`)? 
A. Python 3.7.4

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
A. Darwin-18.7.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 
```
Package    Version
---------- -------
pip        19.3.1
setuptools 42.0.2
wheel      0.33.6
```

4. What did you do?
`pip install -e git+git@github.com:snowflakedb/snowflake-sqlalchemy.git#egg=snowflake-sqlalchemy`

5. What did you expect to see?
Working version of `snowflake-sqlalchemy`, equal to `pip install snowflake-sqlalchemy`

6. What did you see instead?
Breaks python interpreter and pip instead:
```
(.venv) akumar$ python
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "path/to/venv/lib/python3.7/site.py", line 769, in <module>
    main()
  File "path/to/venv/lib/python3.7/site.py", line 746, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "path/to/venv/lib/python3.7/site.py", line 279, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "path/to/venv/lib/python3.7/site.py", line 202, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "path/to/venv/lib/python3.7/site.py", line 170, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

7. Can you set logging to DEBUG and collect the logs?
Doesn't matter because can't invoke Python anyways.

This seems to be related to how the repo is set up using namespace configurations, but any pointers on how to fix this would be helpful. I am trying to install from source, so I can fork it and introduce my custom changes that have not made into the official release.

**Comment by keller00** [comment]
Unfortunately we have no fix for this, the problem is not with our code. It's related to `setuptools`.

We will look into this later, but not in the near future.

For now don't use `-e` is my suggestion.

**Comment by keller00** [comment]
Lets keep an eye on this, as this might be the cause: https://github.com/pypa/pip/issues/6055

**Comment by anujkumar93** [comment]
> For now don't use -e is my suggestion.

Using the following in my requirements.txt file worked. Thanks!
```
git+https://github.com/snowflakedb/snowflake-sqlalchemy#egg=snowflake-sqlalchemy
```
