### ISSUE TITLE
Import failure when installed via external package - packaged as an egg

### ISSUE THREAD

**Issue by edmartin101** [snowflakedb/snowflake-sqlalchemy#148]
1. What version of Python are you using (`python --version`)?
Python 2.7.16
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Darwin-18.7.0-x86_64-i386-64bit
3. What are the component versions in the environment (`pip list`)? 
```
snowflake-sqlalchemy==1.1.16
snowflake-connector-python==2.1.3
```
4. What did you do?
A packaged dependency that includes Snowflake SQL via an egg (i.e a private package installed via Github) will lead to an import issue when run due to line 27 in snowdialect.py, which is not discoverable. However, when the same dependency is packaged and manually installed as a wheel there is no apparent issue with this import path. This issue only impacts Python 2.7 

5. What did you expect to see?
That the external dependency reliant on Snowflake SQLAlchemy would work built as both an egg or as a wheel.
6. What did you see instead?
When installed as an egg the dependency blows up the system. However, when a wheel is built and installed from the same package it works as expected. I would expect that the package making use of Snowflake-sqlalchemy would be installable from both an egg and whl.

7. Can you set logging to DEBUG and collect the logs?
```
from our_library.snowflake_operators import SnowflakeOperator
  File "/server/python/service/lib/python2.7/site-packages/our_library/snowflake_operators.py", line 4, in <module>
    from snowflake.sqlalchemy import VARIANT
  File "/server/python/service/lib/python2.7/site-packages/snowflake/sqlalchemy/__init__.py", line 8, in <module>
    from snowflake.sqlalchemy import snowdialect
  File "/server/python/service/lib/python2.7/site-packages/snowflake/sqlalchemy/snowdialect.py", line 27, in <module>
    from snowflake.sqlalchemy.connectors.constants import UTF8
```

**Comment by keller00** [comment]
Python 2.7 is not supported as of the next `snowflake-python-connector` version.
So if it only affecting legacy version then we will not fix this.
However; if you would like this fixed we'd welcome a PR.

**Comment by edmartin101** [comment]
@keller00 Thanks for the quick feedback. I will take a further look at the feasibility of making a PR.

**Comment by edmartin101** [comment]
Have resolved this issue, by moving the import of VARIANT out of the Snowflake SQLAlchemy package, which while far from ideal has resolved the issue.
