### ISSUE TITLE
BUG with accounts which have subdomains - unable to connect - possible solution in ticket.

### ISSUE THREAD

**Issue by Pangstar** [snowflakedb/snowflake-sqlalchemy#15]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
windows 10 - intel 17 - not sure ..

3. What are the component versions in the environment (`pip list`)? 
1.0.5

4. What did you do?
I am trying to connect using a account with a sub domain - I think I've found the issue with your SnowflakeDialect class in base.py

`
if '.' not in opts['host']: 
`
This on line 356 I don't think there should be an if statement otherwise this doesn't work for connections which have regional subdomains.

5. What did you expect to see?
I expected it to connect and able to query - once I removed this if statement and made 
```
   opts['account'] = opts['host']
            opts['host'] = opts['host'] + '.snowflakecomputing.com'
            opts['port'] = '443'
```
run as part of create_connect_args then everything worked! (for subdomains) but haven't tested for other connection types as I don't have a other connections. 

6. What did you see instead?
I kept getting a bug from sqlalchemy 

`sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 251001: None: Account must be specified`

the snowflake-sqlalchemy code was not in the stack trace

7. Can you set logging to DEBUG and collect the logs?

-- Is this an open project can I submit a pr?

**Comment by Pangstar** [comment]
Would be good to have a test for this too.

**Comment by Pangstar** [comment]
Just to be clear its when account = 'account.eu-central-1'

this will mean account, host and port are not assigned

**Comment by smtakeda** [comment]
Ah, I know this one. I forgot to make a fix in SQLAlchemy dialect when the connector had the same one. Will work on this.

>-- Is this an open project can I submit a pr?

Yes, PR is welcome! But let me work on this specific one.

**Comment by Pangstar** [comment]
:D when will this be updated on pip?

**Comment by smtakeda** [comment]
@Pangstar we usually push the code every Thursday if no blocker is raised.
