### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when autoloading view

### ISSUE THREAD

**Issue by ghost** [snowflakedb/snowflake-sqlalchemy#164]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.7.4

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Windows-10-10.0.17763-SP0

3. What are the component versions in the environment (`pip list`)? 

> Package                            Version
> ---------------------------------- ---------
> aiohttp                            3.6.2
> alabaster                          0.7.12
> anaconda-client                    1.7.2
> anaconda-navigator                 1.9.7
> anaconda-project                   0.8.3
> asn1crypto                         1.0.1
> astroid                            2.3.1
> astropy                            3.2.1
> async-timeout                      3.0.1
> atomicwrites                       1.3.0
> attrs                              19.2.0
> azure-common                       1.1.24
> azure-nspkg                        3.0.2
> azure-storage-blob                 2.1.0
> azure-storage-common               2.1.0
> Babel                              2.7.0
> backcall                           0.1.0
> backports.functools-lru-cache      1.5
> backports.os                       0.1.1
> backports.shutil-get-terminal-size 1.0.0
> backports.tempfile                 1.0
> backports.weakref                  1.0.post1
> bcrypt                             3.1.7
> beautifulsoup4                     4.8.0
> bitarray                           1.0.1
> bkcharts                           0.2
> bleach                             3.1.0
> bokeh                              1.3.4
> boto                               2.49.0
> boto3                              1.9.66
> botocore                           1.12.189
> Bottleneck                         1.2.1
> certifi                            2019.9.11
> cffi                               1.12.3
> chardet                            3.0.4
> Click                              7.0
> cloudpickle                        1.2.2
> clyent                             1.2.2
> colorama                           0.4.1
> comtypes                           1.1.7
> conda                              4.8.2
> conda-build                        3.18.9
> conda-package-handling             1.6.0
> conda-verify                       3.4.2
> contextlib2                        0.6.0
> cryptography                       2.7
> cx-Oracle                          7.2.3
> cycler                             0.10.0
> Cython                             0.29.13
> cytoolz                            0.10.0
> dask                               2.5.2
> decorator                          4.4.0
> defusedxml                         0.6.0
> distributed                        2.5.2
> docutils                           0.15.2
> entrypoints                        0.3
> et-xmlfile                         1.0.1
> fastcache                          1.1.0
> filelock                           3.0.12
> Flask                              1.1.1
> fsspec                             0.5.2
> future                             0.17.1
> gevent                             1.4.0
> glob2                              0.7
> greenlet                           0.4.15
> h5py                               2.9.0
> HeapDict                           1.0.1
> html5lib                           1.0.1
> idna                               2.8
> ijson                              2.6.1
> imageio                            2.6.0
> imagesize                          1.1.0
> importlib-metadata                 0.23
> ipykernel                          5.1.2
> ipython                            7.8.0
> ipython-genutils                   0.2.0
> ipywidgets                         7.5.1
> isort                              4.3.21
> itsdangerous                       1.1.0
> jdcal                              1.4.1
> jedi                               0.15.1
> Jinja2                             2.10.3
> jmespath                           0.9.5
> joblib                             0.13.2
> json5                              0.8.5
> jsonschema                         3.0.2
> jupyter                            1.0.0
> jupyter-client                     5.3.3
> jupyter-console                    6.0.0
> jupyter-core                       4.5.0
> jupyterlab                         1.1.4
> jupyterlab-server                  1.0.6
> keyring                            18.0.0
> kiwisolver                         1.1.0
> lazy-object-proxy                  1.4.2
> libarchive-c                       2.8
> llvmlite                           0.29.0
> locket                             0.2.0
> lxml                               4.4.1
> MarkupSafe                         1.1.1
> matplotlib                         3.1.1
> mccabe                             0.6.1
> menuinst                           1.4.16
> mistune                            0.8.4
> mkl-fft                            1.0.14
> mkl-random                         1.1.0
> mkl-service                        2.3.0
> mock                               3.0.5
> more-itertools                     7.2.0
> mpmath                             1.1.0
> msgpack                            0.6.1
> multidict                          4.7.3
> multipledispatch                   0.6.0
> navigator-updater                  0.2.1
> nbconvert                          5.6.0
> nbformat                           4.4.0
> networkx                           2.3
> nltk                               3.4.5
> nose                               1.3.7
> notebook                           6.0.1
> numba                              0.45.1
> numexpr                            2.7.0
> numpy                              1.16.5
> numpydoc                           0.9.1
> olefile                            0.46
> openpyxl                           3.0.0
> oscrypto                           1.2.0
> packaging                          19.2
> pandas                             0.25.1
> pandocfilters                      1.4.2
> paramiko                           2.7.1
> parso                              0.5.1
> partd                              1.0.0
> path.py                            12.0.1
> pathlib2                           2.3.5
> patsy                              0.5.1
> pep8                               1.7.1
> pickleshare                        0.7.5
> Pillow                             6.2.0
> pip                                19.2.3
> pkginfo                            1.5.0.1
> pluggy                             0.13.0
> ply                                3.11
> prometheus-client                  0.7.1
> prompt-toolkit                     2.0.10
> psutil                             5.6.3
> py                                 1.8.0
> pyarrow                            0.15.1
> pycodestyle                        2.5.0
> pycosat                            0.6.3
> pycparser                          2.19
> pycrypto                           2.6.1
> pycryptodomex                      3.9.7
> pycurl                             7.43.0.3
> pyflakes                           2.1.1
> Pygments                           2.4.2
> PyJWT                              1.7.1
> pylint                             2.4.2
> PyNaCl                             1.3.0
> pyodbc                             4.0.27
> pyOpenSSL                          19.0.0
> pyparsing                          2.4.2
> pyreadline                         2.1
> pyrsistent                         0.15.4
> PySocks                            1.7.1
> pytest                             5.2.1
> pytest-arraydiff                   0.3
> pytest-astropy                     0.5.0
> pytest-doctestplus                 0.4.0
> pytest-openfiles                   0.4.0
> pytest-remotedata                  0.3.2
> python-dateutil                    2.8.0
> pytz                               2019.3
> PyWavelets                         1.0.3
> pywin32                            223
> pywinpty                           0.5.5
> PyYAML                             5.1.2
> pyzmq                              18.1.0
> QtAwesome                          0.6.0
> qtconsole                          4.5.5
> QtPy                               1.9.0
> requests                           2.22.0
> rope                               0.14.0
> ruamel-yaml                        0.15.46
> s3transfer                         0.1.13
> scikit-image                       0.15.0
> scikit-learn                       0.21.3
> scipy                              1.3.1
> seaborn                            0.9.0
> Send2Trash                         1.5.0
> setuptools                         41.4.0
> simplegeneric                      0.8.1
> singledispatch                     3.4.0.3
> six                                1.12.0
> snowballstemmer                    2.0.0
> snowflake-connector-python         2.2.1
> snowflake-sqlalchemy               1.2.1
> sortedcollections                  1.1.2
> sortedcontainers                   2.1.0
> soupsieve                          1.9.3
> Sphinx                             2.2.0
> sphinxcontrib-applehelp            1.0.1
> sphinxcontrib-devhelp              1.0.1
> sphinxcontrib-htmlhelp             1.0.2
> sphinxcontrib-jsmath               1.0.1
> sphinxcontrib-qthelp               1.0.2
> sphinxcontrib-serializinghtml      1.1.3
> sphinxcontrib-websupport           1.1.2
> spyder                             3.3.6
> spyder-kernels                     0.5.2
> SQLAlchemy                         1.3.9
> statsmodels                        0.10.1
> sympy                              1.4
> tables                             3.5.2
> tblib                              1.4.0
> terminado                          0.8.2
> testpath                           0.4.2
> toolz                              0.10.0
> tornado                            6.0.3
> tqdm                               4.36.1
> traitlets                          4.3.3
> unicodecsv                         0.14.1
> urllib3                            1.24.2
> wcwidth                            0.1.7
> webencodings                       0.5.1
> Werkzeug                           0.16.0
> wheel                              0.33.6
> widgetsnbextension                 3.5.1
> win-inet-pton                      1.1.0
> win-unicode-console                0.5
> wincertstore                       0.2
> wrapt                              1.11.2
> xlrd                               1.2.0
> XlsxWriter                         1.2.1
> xlwings                            0.15.10
> xlwt                               1.3.0
> yarl                               1.4.2
> zict                               1.0.0
> zipp                               0.6.0

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Tried to reflect a view `table = Table(table_name, MetaData(schema=schema), autoload=True, autoload_with=bind)`, and received the following error: 

> Traceback (most recent call last):
> File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "<ipython-input-3-448156cb1182>", line 3, in <module>
> autoload=True, autoload_with=bind
> File "<string>", line 2, in __new__
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py", line 128, in warned
> return fn(*args, **kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 506, in __new__
> metadata._remove_table(name, schema)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
> compat.reraise(exc_type, exc_value, exc_tb)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
> raise value
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 501, in __new__
> table._init(name, metadata, *args, **kw)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 595, in _init
> resolve_fks=resolve_fks,
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\schema.py", line 619, in _autoload
> _extend_on=_extend_on,
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2160, in run_callable
> return conn.run_callable(callable_, *args, **kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1612, in run_callable
> return callable_(self, *args, **kwargs)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 459, in reflecttable
> table, include_columns, exclude_columns, resolve_fks, **opts
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\reflection.py", line 707, in reflecttable
> table_name, schema, table, reflection_options
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\reflection.py", line 1009, in _reflect_table_comment
> comment_dict = self.get_table_comment(table_name, schema)
> File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\reflection.py", line 540, in get_table_comment
> self.bind, table_name, schema, info_cache=self.info_cache, **kw
> File "C:\ProgramData\Anaconda3\lib\site-packages\snowflake\sqlalchemy\snowdialect.py", line 586, in get_table_comment
> return {'text': ans['comment'] if ans['comment'] else None}
> TypeError: 'NoneType' object is not subscriptable

5. What did you expect to see?
Nothing.

6. What did you see instead?
An error.

7. Can you set logging to DEBUG and collect the logs?
Was able to patch the code myself by changing the `return` from `get_table_comment()` in snowdialect.py:
```python
def get_table_comment(self, connection, table_name, schema=None, **kw):
        """
        Returns comment of table in a dictionary as described by SQLAlchemy spec
        """
        sql_command = "SHOW /* sqlalchemy:get_table_comment */ " \
                      "TABLES LIKE '{0}'{1}".format(
                                        table_name,
                                        (' IN SCHEMA {0}'.format(self.normalize_name(schema))) if schema else ''
                                    )
        cursor = connection.execute(sql_command)
        ans = cursor.fetchone()
        if ans is None:
            return {'text': None}
        return {'text': ans.get('comment')}
```

**Comment by keller00** [comment]
I think this was fixed by: #154
