### ISSUE TITLE
AWS lambda error: OSError: [Errno 38] Function not implemented

### ISSUE THREAD

**Issue by Jopepato** [snowflakedb/snowflake-sqlalchemy#166]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.8
2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
aws lambda
3. What are the component versions in the environment (`pip list`)? 
asn1crypto==0.24.0
azure-common==1.1.25
azure-core==1.3.0
azure-storage-blob==12.2.0
boto3==1.9.253
botocore==1.12.253
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
docutils==0.15.2
future==0.18.2
idna==2.9
ijson==2.6.1
isodate==0.6.0
jmespath==0.9.5
msrest==0.6.11
oauthlib==3.1.0
pycparser==2.20
pycryptodomex==3.9.7
PyJWT==1.7.1
pyOpenSSL==19.1.0
python-dateutil==2.8.1
pytz==2019.3
requests==2.23.0
requests-oauthlib==1.3.0
s3transfer==0.2.1
six==1.14.0
snowflake-connector-python==1.9.1
snowflake-sqlalchemy==1.2.2
SQLAlchemy==1.3.14
urllib3==1.25.8
4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Hello, I am using aws lambda to connect to the snowflake database. Everything was working fine until I retrieved quite a lot of rows from the database. It happened that I encounter that error. I then checked and saw that the aws lambda does not support multithreading for python, and the library on the back is using it, then I followed this post: https://community.snowflake.com/s/article/Python-connector-2-0-0-incompatible-with-AWS-Lambda

Changed the version of snowflake, created the layer on lambda and uploaded it again. But same error occured, I do not know how to fix it...

**Comment by keller00** [comment]
Version < 2.0.0 is suggested for a different reason.
This is a duplicate of: https://github.com/snowflakedb/snowflake-connector-python/issues/287
Please follow that ticket!
