### ISSUE TITLE
BUG/Issues using COPY keyword in query

### ISSUE THREAD

**Issue by Pangstar** [snowflakedb/snowflake-sqlalchemy#17]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
mac

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Trying to run a snowflake COPY statement from engine.execute using sqlalchemy.

5. What did you expect to see?
I expected it to copy files

6. What did you see instead?
It didn't run as expected - snowflake historical logs showed it ran..  (and when I ran the same query using the snowflake online client it worked) but when executed from sqlalchemy it failed to copy.

i.e. everything looks fine from the client perspective but on snowflake's side it fails - I added COPY to the AUTOCOMMIT_REGEXP regex and everything works as expected

I have created a PR which fixes the issue on my machine. It is just to add the copy reserved keyword to the base.py file in 2 places.

**Comment by smtakeda** [comment]
Thanks for reporting an issue and PR. Looking now.
