### ISSUE TITLE
 No module named snowflake.sqlalchemy

### ISSUE THREAD

**Issue by vishnukelam03** [snowflakedb/snowflake-sqlalchemy#182]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)? python 2.6.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)? linux

3. What are the component versions in the environment (`pip list`)? 
argparse (1.4.0)
boto3 (1.4.1)
botocore (1.4.11)
cas (0.15)
colorama (0.3.3)
distribute (0.7.3)
docutils (0.12)
ethtool (0.6)
freeipa (2.0.0a0)
futures (3.0.5)
iniparse (0.3.1)
iotop (0.3.2)
ipapython (3.0.0)
iwlib (1.0)
jmespath (0.9.0)
kerberos (1.0)
lxml (2.2.3)
M2Crypto (0.20.2)
matplotlib (0.99.1.1)
netaddr (0.7.5)
nose (0.10.4)
numpy (1.4.1)
ordereddict (1.1)
paramiko (1.7.5)
pip (9.0.1)
pyasn1 (0.1.9)
pycrypto (2.0.1)
pycurl (7.19.0)
pygpgme (0.1)
pyOpenSSL (0.10)
pypyodbc (1.3.3)
python-dateutil (2.5.2)
python-default-encoding (0.1)
python-dmidecode (3.10.13)
python-ldap (2.3.10)
python-magic (0.4.12)
python-nss (0.13)
pytz (2010h)
rhnlib (2.5.22)
rhsm (1.9.7)
rsa (3.3)
s3cmd (1.6.1)
s3transfer (0.1.9)
setuptools (15.1)
simplejson (3.3.0)
six (1.10.0)
splunk-sdk (1.3.1)
SSSDConfig (1.9.2)
urlgrabber (3.9.1)
xlsx2csv (0.6.1)
yum-metadata-parser (1.1.2)

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

5. What did you expect to see?

6. What did you see instead?
 No module named snowflake.sqlalchemy

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

I scheduled a job to run for a python script. Initially job was running fine. But from past 1 week job is failing with ModuleError.
I assume that because of snowflake-alchemy module is not installed. Is that so how did the job run all these days?
Any help is appreciated. Thanks.

**Comment by fredrike** [comment]
1. Upgrade to atleast python 3.7
2. Install snowflake-sqlalchemy `pip install snowflake-sqlalchemy` (https://pypi.org/project/snowflake-sqlalchemy/)

**Comment by sfc-gh-aling** [comment]
as @fredrike pointed out, looks like you haven't installed snowflake-sqlalchemy.
please use the pip command to install the snowflake-sqlalchemy.
