### ISSUE TITLE
Unsupported data type 'boolean' when running with superset

### ISSUE THREAD

**Issue by ivankixeye** [snowflakedb/snowflake-sqlalchemy#19]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
3.6.1

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-4.9.27-moby-x86_64-with (alpine docker container)

3. What are the component versions in the environment (`pip list`)? 
See Dockerfile here: https://github.com/ivankixeye/superset/blob/master/Dockerfile

4. What did you do?
When running the docker container, with mounted volume with superset_config.py configured to connect to snowflake e.g.
```python
SQLALCHEMY_DATABASE_URI = 'snowflake://user:pass@account/database/schema?warehouse=whouse'
```
superset startup fails because of this error:
```
DB Creation and initialization failed: (snowflake.connector.errors.ProgrammingError) 002040 (42601): 49122873-702d-463e-9f2e-cef63feffa3c: SQL compilation error:
Unsupported data type 'boolean'. [SQL: '\nCREATE TABLE ab_user (\n\tid INTEGER NOT NULL AUTOINCREMENT, \n\tfirst_name VARCHAR(64) NOT NULL, \n\tlast_name VARCHAR(64) NOT NULL, \n\tusername VARCHAR(64) NOT NULL, \n\tpassword VARCHAR(256), \n\tactive BOOLEAN, \n\temail VARCHAR(64) NOT NULL, \n\tlast_login DATETIME, \n\tlogin_count INTEGER, \n\tfail_login_count INTEGER, \n\tcreated_on DATETIME, \n\tchanged_on DATETIME, \n\tcreated_by_fk INTEGER, \n\tchanged_by_fk INTEGER, \n\tPRIMARY KEY (id), \n\tUNIQUE (username), \n\tUNIQUE (email), \n\tFOREIGN KEY(created_by_fk) REFERENCES ab_user (id), \n\tFOREIGN KEY(changed_by_fk) REFERENCES ab_user (id)\n)\n\n']
```

5. What did you expect to see?
Superset running without initialization errors. 

6. What did you see instead?
See error above

7. Can you set logging to DEBUG and collect the logs?
No, I captured all output from the docker container see above

**Comment by smtakeda** [comment]
Can you run the sql from snowflake UI?
If it doesn't work, it is most likely  Boolean type is not enabled for your
account. Ask the support to enable it.
Sorry I'm AFK.
-- 
Shige Takeda
smtakeda@gmail.com

**Comment by smtakeda** [comment]
A test case is:

create table t(c Boolean);

On Thu, May 18, 2017 at 16:26 Shige Takeda <smtakeda@gmail.com> wrote:

> Can you run the sql from snowflake UI?
> If it doesn't work, it is most likely  Boolean type is not enabled for
> your account. Ask the support to enable it.
> Sorry I'm AFK.
> --
> Shige Takeda
> smtakeda@gmail.com
>
-- 
Shige Takeda
smtakeda@gmail.com

**Comment by ivankixeye** [comment]
Thank you, a submitted a support request. I'll post back when I find out how it goes.

**Comment by smtakeda** [comment]
I assume this is no longer critical. Closing for now.
