### ISSUE TITLE
SNOW-201006: Table Meta-Data with Geography Type throwing error "SAWarning: Did not recognize type 'GEOGRAPHY' of column"

### ISSUE THREAD

**Issue by jpg013** [snowflakedb/snowflake-sqlalchemy#194]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)? 
3.6.11

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Linux-5.4.0-7642-generic-x86_64-with-debian-bullseye-sid

3. What are the component versions in the environment (`pip list`)?
asn1crypto                 1.4.0
azure-common               1.1.25
azure-core                 1.8.1
azure-storage-blob         12.5.0
boto3                      1.14.63
botocore                   1.17.63
certifi                    2020.6.20
cffi                       1.14.3
chardet                    3.0.4
cryptography               2.9.2
docopt                     0.6.2
docutils                   0.15.2
flake8                     3.8.3
GeoAlchemy2                0.8.4
idna                       2.9
importlib-metadata         2.0.0
isodate                    0.6.0
jmespath                   0.10.0
mccabe                     0.6.1
msrest                     0.6.19
oauthlib                   3.1.0
oscrypto                   1.2.1
pip                        20.2.3
psycopg2                   2.8.6
pycodestyle                2.6.0
pycparser                  2.20
pycryptodomex              3.9.8
pyflakes                   2.2.0
PyJWT                      1.7.1
pyOpenSSL                  19.1.0
python-dateutil            2.8.1
pytz                       2020.1
requests                   2.23.0
requests-oauthlib          1.3.0
s3transfer                 0.3.3
setuptools                 40.6.2
setuptools-scm             4.1.2
Shapely                    1.7.1
six                        1.15.0
snowflake-connector-python 2.3.2
snowflake-sqlalchemy       1.2.3
SQLAlchemy                 1.3.19
urllib3                    1.25.10
zipp                       3.2.0

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
I'm trying to retrieve the table meta-data for a Snowflake schema.table. See following code:
    md = MetaData(bind=connection) # connection is snowflake connection
    table = Table(
        table_name,
        md,
        schema=schema_name,
        autoload=True,
        autoload_with=connection
    )
    columns = table.c
    return columns

The table that I am querying for has a Geography type which is not defined in the `ischema_names` and is logging a warning (/sqlalchemy/snowdialect.py:370: SAWarning: Did not recognize type 'GEOGRAPHY' of column) and throwing an exception (site-packages/snowflake/sqlalchemy/snowdialect.py", line 383, in _get_schema_columns
    type_instance = col_type(**col_type_kw)
TypeError: 'NullType' object is not callable)

It looks to me like the Geography type is not implemented, is there a work-around?

5. What did you expect to see?

6. What did you see instead?
![Screenshot from 2020-10-01 11-18-16](https://user-images.githubusercontent.com/7315276/94835863-dddc8200-03d7-11eb-87da-164b66b963e8.png)
7. Can you set logging to DEBUG and collect the logs?
Attached a screenshot of the output.
```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by mariusneo** [comment]
Same issue here. Are there any plans to support this type in snowflake-sqlalchemy?

**Comment by Rustem** [comment]
Same issue is when I try to use GEOGRAPHY, OBJECT, VARIANT and etc snowflakes types.

**Comment by Rustem** [comment]
Could someone help us please? I think i narrowed it down to GEOGRAPHY type, when it is part of table DDL, the sqlalchemy throws this error. Could you implement it please? This is quite urgent to our customers.

**Comment by JJBon** [comment]
`from snowflake.sqlalchemy import snowdialect
from geoalchemy2 import Geometry

snowdialect.ischema_names['GEOGRAPHY'] = Geometry`

Add this to your your proyect . It would enforce the type from geoalchemy into the dialect
