### ISSUE TITLE
get_columns() should reflect string lengths

### ISSUE THREAD

**Issue by cladden** [snowflakedb/snowflake-sqlalchemy#22]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

`3.5.4`

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

`Linux-4.9.49-moby-x86_64-with-debian-8.10`
 
3. What are the component versions in the environment (`pip list`)? 

N/A

4. What did you do?

Created this sqlalchemy model:

```
class Appointment(Base):
    string_with_len = Column(String(100))
```

Using that model, sqlalchemy correctly issued this create table statement:

```
CREATE TABLE appointment (
    string_with_len VARCHAR(100)
);
```

Then, I reflected the table back by doing this:

```
from sqlalchemy import Table
from sqlalchemy.engine.reflection import Inspector
from sqlalchemy import create_engine

engine = create_engine("{0}://{1}:{2}@{3}:{4}/{5}".format('snowflake', db_user, db_pass, db_host, db_port, db_name),
                       connect_args={'sslmode': 'prefer'})
meta = Base.metadata
t = Table('appointment', meta)
insp = Inspector.from_engine(engine)
insp.reflecttable(t, None)
print(t)
```

5. What did you expect to see?

```
Table('appointment', MetaData(bind=None), 
Column('string_with_len', String(100), table=<appointment>),
...
```

6. What did you see instead?

```
Table('appointment', MetaData(bind=None), 
Column('string_with_len', VARCHAR(), table=<appointment>),
...
```

Even though my model has the `string_with_len` column as `Column(String(100))`, I see the reflected type as `VARCHAR`, and _without the max length_. In snowflake-sqlalchemy's `base. SnowflakeDialect.get_columns()`, I see the `character_maximum_length` is being queried from snowflake, but then thrown away. Could `character_maximum_length` be used to determine a more accurate sqlalchemy type with length?

7. Can you set logging to DEBUG and collect the logs?

N/A

**Comment by smtakeda** [comment]
Looking now... looks like a bug. Fixing.
