### ISSUE TITLE
SNOW-367603: Does not work with latest version of certifi module

### ISSUE THREAD

**Issue by mertster** [snowflakedb/snowflake-sqlalchemy#227]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)? 3.7

Error message is (certifi 2021.5.30 (/usr/local/lib/python3.7/site-packages), Requirement.parse('certifi<2021.0.0'), {'snowflake-connector-python'})

**Comment by sfc-gh-mkeller** [comment]
Hi @mertster 
This is actually an issue with `snowflake-connector-python` and it is fixed in master already.
Describing the issue: https://github.com/snowflakedb/snowflake-connector-python/issues/732
