### ISSUE TITLE
SNOW-400125: snowflake-sqlalchemy 1.2.5 NOT supporting sqlalchemy.sql.roles

### ISSUE THREAD

**Issue by Dixon007** [snowflakedb/snowflake-sqlalchemy#235]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
  Python3.8

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
 MacOS

3. What are the component versions in the environment (`pip list`)? 

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

snowflake_engine = create_engine(
            URL(
                account=account_name,
                user=user_name,
                password=user_password,
                database=database,
                schema=schema,
                warehouse=warehouse,
                role=role,
                timezone="America/Los_Angeles",
            )
        )

5. What did you expect to see?
  Appropriate connection to Snowflake with specified role.

6. What did you see instead?
from sqlalchemy.sql.roles import From Clause Role ModuleNotFoundError: No module named 'sqlalchemy.sql.roles'

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```

**Comment by irdvl** [comment]
+1  this change broke our production code

**Comment by erikselin** [comment]
@Dixon007 @irdvl I'm sure you've seen it already just wanted to share that this is due to https://github.com/snowflakedb/snowflake-sqlalchemy/pull/233. In case it helps.
