### ISSUE TITLE
SnowflakeDialect should set the default schema name

### ISSUE THREAD

**Issue by cladden** [snowflakedb/snowflake-sqlalchemy#24]
According to postgres dialect implementation, the default schema name should be set by implementing the `_get_default_schema_name` method. This method will be called once on init instead of every call to `SnowflakeDialect.get_columns` and `SnowflakeDialect.get_primary_keys`. The distinction is important for performance reasons esp. for a schema with many e.g. 100+ tables because `get_columns` and `get_primary_keys` will be called often and reflection will take as long as 10 minutes to complete. The solution might be to implement `_get_default_schema_name` method as show below. 

postgres dialect `_get_default_schema_name` implementation:
https://github.com/zzzeek/sqlalchemy/blob/b60461fb95bc78da16c5eb2948e1aff170b78bbc/lib/sqlalchemy/dialects/postgresql/base.py#L2281

For the `SnowflakeDialect`, my guess at the implementation is:
```
def _get_default_schema_name(self, connection):
    """Return the string name of the currently selected schema from
    the given connection.

    This is used by the default implementation to populate the
    "default_schema_name" attribute and is called exactly
    once upon first connect.

    """
    schema = connection.scalar("select current_schema()")
    return self.normalize_name(schema)
```

**Comment by smtakeda** [comment]
Looking now.
