### ISSUE TITLE
DELETE does not return rowcount 

### ISSUE THREAD

**Issue by jeremylanglois** [snowflakedb/snowflake-sqlalchemy#244]
Python 3.8
Platform: Windows-10-10.018362-SP0

snowflake-sqlalchemy: 1.3.2
SQLAlchemy: 1.4.23

Model definition:

```
from sqlalchemy import Column, Integer, String

class User(Base):
    __tablename__ = 'users'
 
    id = Column(Integer, primary_key=True)
    name = Column(String)
```

Query

```
sess.query(User).filter(User.name == 'foo').delete(synchronize_session=False)
```

**Expected Result**

According to the documentation, the rowcount should be returned:

https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=delete#sqlalchemy.orm.query.Query.delete

https://github.com/zzzeek/sqlalchemy/blob/a7e787a331dd9e5c172a5650397e4e9528ac3632/lib/sqlalchemy/orm/query.py#L3145

According to the dialect configuration and my understanding, the number of deleted rows should indeed be returned:

https://github.com/snowflakedb/snowflake-sqlalchemy/blob/e807fedb31ba93abd9340fd930948a2dad79cb15/snowdialect.py#L112-L120

**Actual Result**

The query returns None whether or not any rows are deleted.

For that matter, UPDATE seems to have the same issue.

**Comment by rvpeters** [comment]
Were you able to find any workaround for this? I am seeing the same issue locally

**Comment by sfc-gh-hachouraria** [comment]
The following appears to be the cause of this behavior:

1. SQLAlchemy [closes the underlying cursor object](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/orm/query.py#L2980-L3040) before returning the cursor's row count when performing a bulk delete
2. Within Snowflake's python connector, a [cursor close call invokes an internal reset method](https://github.com/snowflakedb/snowflake-connector-python/blob/2ccd3c811958170854ff4cac159e7c125bf8b4f3/src/snowflake/connector/cursor.py#L387-L397) that [erases the known row count value](https://github.com/snowflakedb/snowflake-connector-python/blob/2ccd3c811958170854ff4cac159e7c125bf8b4f3/src/snowflake/connector/cursor.py#L1172-L1174)
3. Ultimately [a 'None' value is returned to the caller](https://github.com/snowflakedb/snowflake-connector-python/blob/2ccd3c811958170854ff4cac159e7c125bf8b4f3/src/snowflake/connector/cursor.py#L282-L284) when it seeks the row count property

I am not fully clear about how `cursor.reset()` is used directly but to compare against SQLite's DB-API cursor implementation as a reference, the [close of the cursor does not erase the row count value](https://github.com/python/cpython/blob/3.10/Modules/_sqlite/cursor.c#L985-L1016).

If there's a legitimate use-case for `cursor.reset()` (result reuse?) then perhaps the `cursor.close()` can call an alternative form of reset that does not erase row count information while marking the cursor unusable as the specification requires.

**Comment by rvpeters** [comment]
Hi @sfc-gh-hachouraria thanks for the explanation, I tested locally by commenting out the line in the Snowflake python connector that resets the row count value in the cursor reset method and am now getting the proper row count returned for both UPDATE and DELETE
