### ISSUE TITLE
foreign key names should be normalized 

### ISSUE THREAD

**Issue by cladden** [snowflakedb/snowflake-sqlalchemy#25]
Foreign key names should be normalized for proper reflection. I believe the `foreign_key_map` is built by name in `get_foreign_keys`, here:
https://github.com/snowflakedb/snowflake-sqlalchemy/blob/master/base.py#L484

I think the fix may be a 1 line change to wrap the `name` value with a call to `self.normalize_name`, e.g.:

```
def get_foreign_keys(self, connection, table_name, schema=None, **kw):
...
        foreign_key_map = {}
        for row in result:
-           name = row[n2i['fk_name']]
+           name = self.normalize_name(row[n2i['fk_name']])
            constrained_table = self.normalize_name(row[n2i['fk_table_name']])
...
```

**Comment by smtakeda** [comment]
Thanks for reporting an issue. WIP.
