### ISSUE TITLE
SNOW-522232: SAWarning: Dialect snowflake:snowflake will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.

### ISSUE THREAD

**Issue by cyaris** [snowflakedb/snowflake-sqlalchemy#265]
Python 3.8.9
macOS-11.6.2-x86_64-i386-64bit
snowflake-connector-python: 2.7.2
snowflake-sqlalchemy: 1.3.3
SQLAlchemy: 1.4.28

I imported the following...

```
import pandas as pd
from sqlalchemy import create_engine
from snowflake.sqlalchemy import URL
import snowflake.connector
```

Then, I created a new engine and executed my first query...

```
url = URL(CREDENTIALS) 
engine = create_engine(url)
connection = engine.connect()

pd.read_sql(QUERY, connection)
```

Received the following warning...

> /Users/NAME/.local/lib/python3.8/site-packages/snowflake/sqlalchemy/snowdialect.py:206: SAWarning: Dialect snowflake:snowflake will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)

**Comment by YCaillaud-betclic** [comment]
I have the same warning.

With these settings :

Python 3.7.9  **(cyaris has 3.8.9)**
windows 64 bit
snowflake-connector-python: 2.7.2
snowflake-sqlalchemy: 1.3.3
SQLAlchemy: 1.4.29          **(cyaris has 1.4.28)**

**Comment by Data-Zen** [comment]
I have the same issue.  Need fix ASAP

**Comment by pablorf-ind** [comment]
We are also seeing this with the last version of both libraries.

**Comment by uncle-samm** [comment]
For those who'd like this warning to be disabled do this before creating an engine:

```
from snowflake.sqlalchemy.snowdialect import SnowflakeDialect

SnowflakeDialect.supports_statement_cache = False
```

**Comment by sfc-gh-mkeller** [comment]
We unfortunately don't fully support SQLAlchemy 1.4.0 features yet.

@sfc-gh-hkapre and @sfc-gh-sbommakanty for visibility

**Comment by allenlawrence94** [comment]
Could we just set `supports_statement_cache` to `False` for now? Preferably in this package, rather than users doing it manually.

**Comment by sfc-gh-mkeller** [comment]
I'm for setting the attribute to `False` for now.

I'd put a comment with the variable like:

```
# TODO: support SQL caching, for more info see: https://docs.sqlalchemy.org/en/14/core/connections.html#caching-for-third-party-dialects
supports_statement_cache = False
```

@allenlawrence94 would you like to submit a PR for this?

**Comment by allenlawrence94** [comment]
Sure! https://github.com/snowflakedb/snowflake-sqlalchemy/pull/275
