### ISSUE TITLE
SNOW-589962: Enhance CreateFileFormat command

### ISSUE THREAD

**Issue by chaami** [snowflakedb/snowflake-sqlalchemy#291]
The current command only supports a replace if exits.

Ideally the command would support:
- a file format comment
- the if not exists option

This would make the command better support the [Snowflake CREATE FILE FORMAT](https://docs.snowflake.com/en/sql-reference/sql/create-file-format.html).

**Comment by sfc-gh-mraba** [comment]
Resolved by #739 (merged in 3b4ed60). `CreateFileFormat` now supports `if_not_exists` and `comment` options for closer parity with Snowflake's `CREATE FILE FORMAT`. The `COMMENT` literal is escaped with `escape_string_literal_interior` (doubling both single quotes and backslashes), consistent with the rest of the DDL compiler.
