### ISSUE TITLE
SNOW-606810: Insert List into ARRAY column

### ISSUE THREAD

**Issue by ThomasJRyan** [snowflakedb/snowflake-sqlalchemy#299]
## What is the current behavior?
Currently it doesn't seem possible (as far as I'm able to tell) to insert a List into an ARRAY typed column.

## What is the desired behavior?
The desired behaviour would be to be able to do this:
```python
from my_app import app
from snowflake.sqlalchemy import ARRAY

db = SQLAlchemy(app)

class MyTable(db.Model):
    col = db.Column(ARRAY)

db.create_all()

obj = MyTable(col = ['Hello', 'World'])

db.session.add(obj)
db.session.flush()

# Error is raised
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 002020 (21S01): SQL compilation error
Insert value list does not match column list expecting 1 but got 2
[SQL: INSERT INTO mytable (col) VALUES (%(col)s)]
[parameters: {'col': ['Hello', 'World]}]
```

I know the error is coming from `snowflake.connector`, but if I'm understanding it correctly, the error is being raised because the generated query
```sql
INSERT INTO mytable (col) VALUES (['Hello', 'World']);
```
isn't actually valid in Snowflake. It'd probably need to be converted to something like
```sql
INSERT INTO mytable (col) SELECT PARSE_JSON('["Hello", "World"]');
```
to work properly.

I'm not really sure of a way to do this outside of just writing out the query myself which seems counterintuitive to the purpose of SQLAlchemy. If I'm missing something obvious I apologize for the bother

## How would this improve `snowflake-connector-python`?
Would allow users to easily add data to ARRAY columns

## References, Other Background
Any examples are using Flask-SQLAlchemy to act as a wrapper for Snowflake-SQLAlchemy. I'm pretty sure this is missing from the latter rather than being a bug of the former. Please correct me if I'm wrong

**Comment by ThomasJRyan** [comment]
Sorry @shahargl I meant to reply a week ago. This is an effective workaround and has unstuck me. Thank you very much for it

Would still be nice to see a more permanent fix someday though. I might look into a way to contribute it but I can't guarantee I'd be capable enough to implement a proper solution

**Comment by shahargl** [comment]
Agree, but they are not showing love to this repo

**Comment by sfc-gh-hachouraria** [comment]
As another alternative method SQLAlchemy's `Insert.from_select` could also work to satisfy the `INSERT INTO … SELECT` requirement for direct variant values:

```python
from sqlalchemy import select, insert, func

s = select(func.ARRAY_CONSTRUCT(['Hello', 'World']))
i = insert(MyTable).from_select([MyTable.col], s)
session.execute(i)
```
