### ISSUE TITLE
DESCRIBE TABLE result is not cached for get_columns and get_primary_keys

### ISSUE THREAD

**Issue by cladden** [snowflakedb/snowflake-sqlalchemy#30]
As far was I can tell, the exact same `DESCRIBE TABLE ...` command is called in both `get_columns()` and `get_primary_keys()`. During reflection, this causes negative performance issues. If DESCRIBE TABLE has to be called twice, could the result be cached to reduce one of the calls?

As an example, if a new caching method stored the `DESCRIBE TABLE ...` n2i, result:

```
@reflection.cache
def describe_table(self, connection, full_table_name, **kw):
    result = connection.execute(
            "DESCRIBE TABLE /* sqlalchemy */ {0}".format(
                    full_table_name))
    n2i = self.__class__._map_name_to_idx(result)
    result = [row for row in result]
    return n2i, result
```

Then, it could potentially be used in this manner...

In `get_primary_keys()`:
```
@reflection.cache
def get_primary_keys(self, connection, table_name, schema=None, **kw):
    schema = schema or self.default_schema_name
    if not schema:
        row = connection.execute("SELECT CURRENT_SCHEMA()").fetchone()
        schema = self.normalize_name(row[0])
    full_table_name = self._denormalize_quote_join(schema, table_name)

    n2i, result = self.describe_table(connection, full_table_name, **kw)
    ...
```

In `get_columns()`:
```
@reflection.cache
def get_columns(self, connection, table_name, schema=None, **kw):
    schema = schema or self.default_schema_name
    if not schema:
        row = connection.execute("SELECT CURRENT_SCHEMA()").fetchone()
        schema = self.normalize_name(row[0])
    full_table_name = self._denormalize_quote_join(schema, table_name)

    n2i, result = self.describe_table(connection, full_table_name, **kw)
    ...
```

I'm sure there's probably cleaner ways than the above to implement the caching and/or refactor to reduce the repeated code blocks :-)

**Comment by smtakeda** [comment]
can you take a look at the latest update?
https://github.com/snowflakedb/snowflake-sqlalchemy/commit/afb589537c9bd176de0334e6790ff7d2ad7021b0

Regression Tests passed. will push it part of v1.0.9 anyway.

**Comment by cladden** [comment]
I left a few comments on https://github.com/snowflakedb/snowflake-sqlalchemy/commit/afb589537c9bd176de0334e6790ff7d2ad7021b0 

In summary, the reflection.cache is not working because to use the `@reflection.cache`, the new methods must accept `**kw` as an argument, and `*kw` must be passed in on every invocation as appropriate.

**Comment by smtakeda** [comment]
Ah, good point. I've fixed it and raised PR again:
https://github.com/snowflakedb/snowflake-sqlalchemy/pull/33

Also added `cache_column_metadata=True` to the DSN so that all column metadata are cached when `get_table_names` called.

**Comment by smtakeda** [comment]
Closing as this was fixed. @cladden, Please reopen this if you see further issue.
