### ISSUE TITLE
SNOW-638844: Unrecognizable column DATE 

### ISSUE THREAD

**Issue by Dixon007** [snowflakedb/snowflake-sqlalchemy#328]
snowflake/sqlalchemy/snowdialect.py:541 SAWarning: Did not recognize type 'DATE' of column 'date'

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-aling** [comment]
hey @Dixon007 , thanks for reaching out.

We've identified the issue and plan for a bug fix release, please follow the progress here: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/333

**Comment by sfc-gh-aling** [comment]
thanks for your patience, we have released 1.4.1 which fixed the issue. please upgrade to the latest one and take a try.
I'm closing the issue now, feel free to reach out if you're still encountering the issue or see other issues.
