### ISSUE TITLE
SNOW-638843: TypeError: 'NullType' object is not callable V1.4.0 

### ISSUE THREAD

**Issue by Dixon007** [snowflakedb/snowflake-sqlalchemy#330]
Recently updated to snowflake-sqlalchemy on our production pipelines and everything broke. See error message

 WARNING - /home/airflow/.local/lib/python3.7/site-packages/snowflake/sqlalchemy/snowdialect.py:541 SAWarning: Did not recognize type 'DATE' of column 'order_date'
[2022-08-01, 15:47:52 UTC] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):

Note: there no column called order_date within any of the SQL queries used

**Comment by sfc-gh-mkeller** [comment]
recreate jira

**Comment by sfc-gh-aling** [comment]
hey @Dixon007 , thanks for reaching out.

We've identified the issue and plan for a bug fix release, please follow the progress here: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/333

**Comment by sfc-gh-aling** [comment]
thanks for your patience, we have released 1.4.1 which fixed the issue. please upgrade to the latest one and take a try.
I'm closing the issue now, feel free to reach out if you're still encountering the issue or see other issues.
