### ISSUE TITLE
SNOW-645168: Binding data in type (bytesio) is not supported.

### ISSUE THREAD

**Issue by janb-frontify** [snowflakedb/snowflake-sqlalchemy#337]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   Python 3.9.12

2. What operating system and processor architecture are you using?

   macOS-12.5-arm64-arm-64bit

3. What are the component versions in the environment (`pip freeze`)?

   aiohttp==3.8.1
aiosignal==1.2.0
asn1crypto==1.5.1
async-timeout==4.0.2
attrs==22.1.0
Authlib==1.0.1
boto3==1.23.4
botocore==1.26.10
cached-property==1.5.2
certifi==2022.6.15
cffi==1.15.1
charset-normalizer==2.0.12
cryptography==36.0.2
frozenlist==1.3.1
fsspec==2022.7.1
idna==3.3
isodate==0.6.1
jmespath==1.0.1
lxml==4.8.0
multidict==6.0.2
numpy==1.23.1
oscrypto==1.3.0
pandas==1.4.3
platformdirs==2.5.2
pyarrow==6.0.1
pycparser==2.21
pycryptodomex==3.15.0
PyJWT==2.4.0
pyOpenSSL==22.0.0
python-dateutil==2.8.2
pytz==2022.2
PyYAML==5.4.1
requests==2.27.1
requests-file==1.5.1
requests-toolbelt==0.9.1
s3fs==0.4.2
s3transfer==0.5.2
simple-salesforce==1.12.1
six==1.16.0
snowflake-connector-python==2.7.8
snowflake-sqlalchemy==1.3.4
SQLAlchemy==1.4.40
urllib3==1.26.11
yarl==1.8.1
zeep==4.1.0

4. What did you do?

   Trying to bind File-like object (BytesIO) in the execute statement is not working.

    f = BytesIO()
            df.to_json(f, orient="records", date_format="iso")
            connection.execute(
                f"PUT file://example.txt @{stage} auto_compress=true;", file_stream=f
            )
     f.close()

   Following error is displayed:
   sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 252004: 252004: Failed processing             pyformat-parameters: 255001: 255001: Binding data in type (bytesio) is not supported.

   With cursor from Python snowflake connector, it's working.
     f = BytesIO()
     df.to_json(f, orient="records", date_format="iso")
     cnx.cursor().execute(
         f"PUT file://example.txt @{stage} auto_compress=true;", file_stream=f
    )
     f.close()

5. What did you expect to see?

   Command should have been successfully executed.

**Comment by sfc-gh-aling** [comment]
recreate jira

**Comment by sfc-gh-aling** [comment]
thanks for reaching out! we'll take a look into it
