### ISSUE TITLE
Connection URL parameters aren't documented anywhere

### ISSUE THREAD

**Issue by kheuton** [snowflakedb/snowflake-sqlalchemy#35]
I'm developing with snowflake-sqlalchemy, and in my organization control over the snowflake `ROLE` is important. I couldn't find any documentation either on snowflake's website, the snowflake-connector-python docs, or the snowflake-sqlalchemy docs indicating that it might be possible to specify role in a connection URL. ~~However, it looks like adding `?roleName=` to the connection URL would do the trick, based on the [python connector code](https://github.com/snowflakedb/snowflake-connector-python/blob/6c3e666ef6c388a3bde2b190256f88a615259196/auth.py#L156).~~ As mentioned below, this was incorrect, and `role` is the proper parameter. 

Where should this be documented? I feel as if this repo is the appropriate place, as it contains the url constructor util and is also a heavy user of the URLs. Would it be appropriate to submit a PR documenting the ~~`roleName`~~ (and possibly other) url connection parameters?

**Comment by smtakeda** [comment]
Thanks for pointing out missing doc for the parameter. `role` can be specified in as part of connection parameters, e.g.,:

```
engine = create_engine(URL(
    account = 'abc123',
    user = 'testuser1',
    password = '0123456',
    database = 'testdb',
    schema = 'public',
    warehouse = 'testwh',
    role='myrole',
    timezone = 'America/Los_Angeles',
))
```
`?roleName=` is a parameter for the backend REST API call.
I'll update the doc later today.

**Comment by smtakeda** [comment]
Can you please review the doc? https://github.com/snowflakedb/snowflake-sqlalchemy/pull/36
Meanwhile I'm asking @markpeters-snow to review it.

**Comment by kheuton** [comment]
Will do, testing the role parameter now.
