### ISSUE TITLE
SNOW-811162: Python pip complains that snowflake-sqlalchemy requires sqlalchemy < 2.0.0

### ISSUE THREAD

**Issue by Jan-Kowalik-mulberryrisk** [snowflakedb/snowflake-sqlalchemy#413]
Python pip complains that snowflake-sqlalchemy requires sqlalchemy < 2.0.0. 
Do I need to downgrade the sqlalchemy package for this to work?

**Comment by sfc-gh-achandrasekaran** [comment]
Hi @Jan-Kowalik-mulberryrisk - yes Snowflake's SQL Alchemy does not support SQL Alchemy 2.0 just yet - this is planned next quarter. You'd need to downgrade the sql alchemy package.
