### ISSUE TITLE
SNOW-878116: `CopyInto` does not support the `PARTITION BY` clause

### ISSUE THREAD

**Issue by azban** [snowflakedb/snowflake-sqlalchemy#430]
## What is the current behavior?

`CopyInto` does not support the `PARTITION BY` clause

## What is the desired behavior?

`CopyInto` supports the `PARTITION BY` clause

## How would this improve `snowflake-connector-python`?
 
This would allow users to use the `PARTITION BY` clause which is a documented feature of the `COPY INTO` statement

## References, Other Background

https://docs.snowflake.com/en/sql-reference/sql/copy-into-location

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this with us, especially the contribution in the PR to address the need ! asked review from the team, hopefully they can review soon.

**Comment by afavaro** [comment]
@sfc-gh-dszmolka

Any chance we could get a review on the PR that @azban provided? We're still maintaining our own fork of this library so that we can use this feature.

**Comment by sfc-gh-dszmolka** [comment]
(reopening so we can keep track when the merged change will be released)

**Comment by sfc-gh-dszmolka** [comment]
released with snowflake-sqlalchemy v1.7.1
