### ISSUE TITLE
SNOW-889543: Multiple vulnerabilities introduced through cryptography <41.0.2

### ISSUE THREAD

**Issue by f0rtun3** [snowflakedb/snowflake-sqlalchemy#434]
## What is the current behavior?

Security Vulnerability introduced through cryptography. Version constraint imposed on cryptography (cryptography >=3.1.0,<41.0.0 ) does not allow for upgrade.

## What is the desired behavior?

A more secure cryptography version.

## How would this improve `snowflake-connector-python`?
Upgrade cryptography transitive dependency constraint to >=41.0.2

## References, Other Background

https://security.snyk.io/package/pip/cryptography

**Comment by sfc-gh-sfan** [comment]
This is an issue more suited for https://github.com/snowflakedb/snowflake-connector-python, but in the latest release, we've bumped the upper bound to `<42.0.0`: https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L47
