### ISSUE TITLE
SNOW-1057479: ImportError: cannot import name 'string_types' from 'sqlalchemy.util.compat'

### ISSUE THREAD

**Issue by Abe410** [snowflakedb/snowflake-sqlalchemy#467]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

3.10.12

3. What are the component versions in the environment (`pip freeze`)?

   Using snowflake-sqlalchemy == 1.5.1

4. What did you do?

   ```python

    from snowflake.sqlalchemy import URL
   ```

5. What did you expect to see?

   Module to import as usual

6. Can you set logging to DEBUG and collect the logs?

```
Traceback (most recent call last):
  File "/home/airflow/tm-ml-chat/example.py", line 71, in <module>
    from new import agent_executor
  File "/home/airflow/tm-ml-chat/new.py", line 68, in <module>
    from snowflake.sqlalchemy import URL
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/sqlalchemy/__init__.py", line 30, in <module>
    from . import base, snowdialect
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/sqlalchemy/base.py", line 20, in <module>
    from sqlalchemy.util.compat import string_types
ImportError: cannot import name 'string_types' from 'sqlalchemy.util.compat' (/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py)
```

**Comment by sfc-gh-dszmolka** [comment]
hi and thanks for submitting this issue. tried it and seems to be working:
```
 python
Python 3.11.7 (main, Jan 17 2024, 06:37:55) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from snowflake.sqlalchemy import URL
>>> 
```

so to investigate this further, would it be please possible to send the full output of `pip freeze` ? thank you in advance !

**Comment by sfc-gh-dszmolka** [comment]
looks like both https://github.com/snowflakedb/snowflake-sqlalchemy/issues/467 and https://github.com/snowflakedb/snowflake-sqlalchemy/issues/445 are duplicates of
 https://github.com/snowflakedb/snowflake-sqlalchemy/issues/452 and caused by the library not yet supporting SQLAlchemy 2.0

implementation efforts on #380 - thank you for bearing with us !
