### ISSUE TITLE
Best practice for doing cross database joins using ORM

### ISSUE THREAD

**Issue by tchoedak** [snowflakedb/snowflake-sqlalchemy#47]
### Question

Hi there, in snowflake we often have multiple databases, with their own set of schemas, and tables inside those schemas. Ideally data shouldn't have to move between these databases nor schemas, but in practice they often do.

One use case is when there might be valuable data between two different databases. In my example, I'm going to reference database `A` and database `B` which has schemas `ant` and `babboons`, which has tables `apples` and `bananas` respectively.

Through a direct query using snowflake SQL, you could implement a join like
```
select
    *
from A.ant.apples a
join B.babboons.bananas b
    on a.id = b.id
```

How can you implement a cross database join like the above example using a single session through the ORM interface? my understanding is that a session can only point towards one database.

The query would look like such:
```
# assume session was created with database=A
query = session.query(Ant.id, Banana.id)\
    .join(Banana, Ant.id == Banana.id)
```

This would obviously fail because the query would search for a A.babboons.banana (Database A).

Can this be done through the ORM interface without dropping to SQL? If so, what's the best practice in doing this?

### Issue Template

Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Python 2.7.12

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-4.9.76-3.78.amzn1.x86_64-x86_64-with-glibc2.2.5

3. What are the component versions in the environment (`pip list`)? 

snowflake-connector-python==1.5.8
snowflake-sqlalchemy==1.1.0

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

5. What did you expect to see?

N/A

6. What did you see instead?

N/A

7. Can you set logging to DEBUG and collect the logs?

N/A

**Comment by kevinjfoley** [comment]
It seems there is support for multi part schemas in SQL Alchemy as SQL Server also has the concept of multiple databases on one server - http://docs.sqlalchemy.org/en/latest/dialects/mssql.html#multipart-schema-names 

I tried using the same syntax of setting schema equal to `database.schema` but it looks like `snowflake-sqlalchemy` quotes the entire thing and passes `"DATABASE.SCHEMA"` which creates errors.

**Comment by smtakeda** [comment]
ok, sounds like if Snowflake SQLAlchemy do quotes `"DATABASE"."SCHEMA"`, then it will be resolved?

**Comment by kevinjfoley** [comment]
I believe that should fix things but I wasn't able to test it out and confirm.  It would definitely fix the error I was encountering when trying to autoload a table, however there may be additional errors after that point.

**Comment by tchoedak** [comment]
@smtakeda that might work. As far as I can tell, there should be no reason why we can't treat the pairing of `DATABASE` and `SCHEMA` as a unique schema e.g. `"DATABASE"."SCHEMA"`. We're still able to query multiple snowflake databases within a single session and engine, so theoretically just parsing the schema from the below example and formatting it for snowflake compatibility should produce the right query under the hood.

```python
class User(Base):
    __tablename__ = 'users'
    __table_args__ = {'schema': 'production.dimm'}
    id = Column(Integer, primary_key=True)

query = session.query(User.id)
str(query)
```

```bash
select USER.ID from "PRODUCTION"."DIMM".users
```

**Comment by smtakeda** [comment]
I think I've fixed the issue. https://github.com/snowflakedb/snowflake-sqlalchemy/pull/48
It would be great if somebody review the change. Thank you.

**Comment by smtakeda** [comment]
Committed the fix after the improvement. Let me know if you have any issue. Thanks.

**Comment by smtakeda** [comment]
This fix will be released on May 17th.

**Comment by tchoedak** [comment]
@smtakeda Thank you, @kevinjfoley and I confirmed this is working now :).

**Comment by felixramirezreyes** [comment]
Thanks tchoedak. Work for me
