### ISSUE TITLE
SNOW-1345376: SnowflakeDDLCompiler overrides get_identity_options but doesn't use it anywhere

### ISSUE THREAD

**Issue by DanielTatarkin** [snowflakedb/snowflake-sqlalchemy#494]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   `Python 3.9.X`

2. What operating system and processor architecture are you using?

   `macOS-14.4.1-arm64-arm-64bit`

3. What are the component versions in the environment (`pip freeze`)?

   unrelated

4. What did you do?

  Creating SQLAlchemy ORM models with AUTOINCREMENT | IDENTITY sequence does not read identity options in order to apply them to SEQUENCE objects or Columns with AUTOINCREMENT | IDENTITY.

5. What did you expect to see?

   Identity options should be set on SEQUENCE objects and/or Columns with AUTOINCREMENT | IDENTITY.

   See examples:
- [Base DDLCompiler usage in visit_create_sequence](https://github.com/sqlalchemy/sqlalchemy/blob/7adc7404acc691698e30c362a8ec03af2bd426fd/lib/sqlalchemy/sql/compiler.py#L6863)
- [Google SpannerDDLCompiler usage in visit_create_sequence](https://github.com/googleapis/python-spanner-sqlalchemy/blob/47438b1dd3cd1b859d519d07f7671948021fa1d6/google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py#L501)
- [Oracle OracleDDLCompiler usage in visit_identity_column](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/oracle/base.py#L1360)

6. Can you set logging to DEBUG and collect the logs?

   N/A

**Comment by sfc-gh-dszmolka** [comment]
hi - thank you for raising this and also for the suggested solution, appreciated! we'll review.

**Comment by sfc-gh-dszmolka** [comment]
i see the associated PR has been merged earlier this year and since then there was at least 1 release
