### ISSUE TITLE
SNOW-1475363: Adding a monthly downloads badge to the README

### ISSUE THREAD

**Issue by ayushjain01** [snowflakedb/snowflake-sqlalchemy#502]
Just a suggestion. I have been working on building a badge system for python packages to display some stats like monthly downloads etc. You can view them here at - https://piptrends.com/widgets/snowflake-sqlalchemy

We are trying to build a learning forum at pip Trends, where developers can find everything they need to get started with python and python packages. This issue is just to share something we have built.

**Comment by ayushjain01** [comment]
I will raise the PR, if this seems like a good thing to add to the README. Here's an example badge -  [![snowflake-sqlalchemy Downloads Last Month](https://assets.piptrends.com/get-last-month-downloads-badge/snowflake-sqlalchemy.svg 'snowflake-sqlalchemy Downloads Last Month by pip Trends')](https://piptrends.com/package/snowflake-sqlalchemy)

The badge links to snowflake-sqlalchemy's pip Trends page, where we display some stats and documentation. Soon we plan on adding simple getting started articles etc. as well to this page.(These are open to contributions)
If required, this link can be removed. This issue is only to share the badge we have built.

**Comment by sfc-gh-dszmolka** [comment]
hi - thank you for the suggestion. The PR is appreciated if you feel doing it !

**Comment by emdneto** [comment]
I recommend rejecting this PR. It seems like suspicious activity as noticed by @ixmatus . He also opened a PR against our repo here https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2547
