### ISSUE TITLE
SNOW-1843517: Double the amount of queries executed during table reflection in update 1.7.0

### ISSUE THREAD

**Issue by phillip-parrott** [snowflakedb/snowflake-sqlalchemy#554]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using?

   3.11.8

2. What operating system and processor architecture are you using?

   Linux

3. What are the component versions in the environment (`pip freeze`)?

   `snowflake-sqlalchemy = "1.7.0"`

4. What did you do?

   After the latest update to `1.7.0`, we began seeing double the number of queries for each reflection. We believe it is due to the `get_multi_prefixes` function in [snowdialect.py](https://github.com/snowflakedb/snowflake-sqlalchemy/blob/62bab2f82da8d7d7e0f846eafa57aee397973d8f/src/snowflake/sqlalchemy/snowdialect.py#L918).

5. What did you expect to see?

   We would expect no changes, but this doubled reflection time. For small amounts of tables this isn't an issue, but we have a big project where we are reflecting hundreds of tables.

**Comment by sfc-gh-dszmolka** [comment]
PR https://github.com/snowflakedb/snowflake-sqlalchemy/pull/556 should fix this, under review.

**Comment by sfc-gh-dszmolka** [comment]
change seems to be merged, which autoclosed this issue. Reopening to be able to keep track with the release.

**Comment by sfc-gh-dszmolka** [comment]
released with snowflake-sqlalchemy v1.7.2
