### ISSUE TITLE
Querying Semistructured Data with Column Elements

### ISSUE THREAD

**Issue by alanapradhan** [snowflakedb/snowflake-sqlalchemy#56]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)? 3.6.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)? Darwin-16.7.0-x86_64-i386-64bit

3. Question: My question is how do I use semistructured data in my sqlalchemy orm queries. I am interested in referencing the semistructured data in the SELECT, JOINs and the WHERE clause. 

I would like to generate a query like this with snowflake-sqlalchemy, however I'm not sure how to generate the snowflake semistructured data syntax `table.column_name:key`:

```
SELECT activity.blob:document_id
FROM event
JOIN event ON activity.blob:event_id == event.id
WHERE activity.blob:document_id > 5
```
Thank you for your help,
Alana

**Comment by smtakeda** [comment]
The current version of Snowflake SQLAlchemy doesn't support the JSON type natively.
http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.JSON
We don't have a plan in the short term, though I'm not sure how it would be helpful for this issue. Any suggestion of using API and design would be appreciated.

**Comment by ztane** [comment]
The `JSON` type as it works in PostgreSQL would allow writing the query as

```
    Query(Activity)
        .join(Event, Activity.blob['event_id'] == Event.id)
        .filter(Activity.blob.blob['document_id'] > 5)
```

which is a significant improvement

**Comment by alexscott-ff** [comment]
Looks like this hasn't been updated in awhile.. Is the somewhat hacky solution proposed above still the best way to do this?

**Comment by crstnrm** [comment]
Any update on this matter?
