### ISSUE TITLE
Interest in CopyIntoS3 command

### ISSUE THREAD

**Issue by sburns** [snowflakedb/snowflake-sqlalchemy#58]
(I removed the ISSUE_TEMPLATE as I don't have an issue, just want to gauge general interest).

We're exploring migrating to snowflake from redshift and we heavily depend on [sqlalchemy_redshift.commands.UnloadFromSelect](https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/blob/master/sqlalchemy_redshift/commands.py#L107). Is there any interest in providing a `snowflake_sqlalchemy.commands.CopyIntoS3`?

I will probably start writing this in a week or so and would be more than happy to contribute it if its something you would feel valuable for the project.

**Comment by smtakeda** [comment]
Yes, you are welcome to contribute to the Snowflake SQLAlchemy improvement!

**Comment by smtakeda** [comment]
The documentation is not complete but v1.1.8 introduced `CopyInto`.
Please try and let us know if you have questions.
