### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by NoazDad** [snowflakedb/snowflake-sqlalchemy#70]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?
Python 3.6.5

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?
Darwin-17.7.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
csvsql -i postgresql Medicare_Provider_Charge_Inpatient_DRG100_FY2011.csv //this works
csvsql -i snowflake Medicare_Provider_Charge_Inpatient_DRG100_FY2011.csv /this throws the error

5. What did you expect to see?
Output the DDL for the Create Table statement.

6. What did you see instead?
'module' object is not callable.

**Comment by smtakeda** [comment]
Sorry for late response. looking now.

**Comment by smtakeda** [comment]
The fix would be in `setup.py`:
```
    entry_points={
        'sqlalchemy.dialects': [
            'snowflake=snowflake.sqlalchemy.base:SnowflakeDialect',
        ]
    },
```
