### ISSUE TITLE
Import from non existent module

### ISSUE THREAD

**Issue by bkyryliuk** [snowflakedb/snowflake-sqlalchemy#85]
https://github.com/snowflakedb/snowflake-sqlalchemy/blob/80191ba13bf7d0216e2d18225120803383034ed0/snowdialect.py#L23

This imports from the un-existent package and couples this lib with the https://github.com/snowflakedb/snowflake-connector-python

This and name-spacing makes it probably impossible to use in the bazel build system

It would be nice to either merge those 2 libraries or completely decouple them and put into separate directories.

E.g. if you rename the package, imports stop working and you see:
```
ValueError: Attempted relative import beyond toplevel package```

**Comment by smtakeda** [comment]
This was released in v1.1.11
