### ISSUE TITLE
snowflake-sqlalchemy breaks table creation with indices for all dialects

### ISSUE THREAD

**Issue by micaelbergeron** [snowflakedb/snowflake-sqlalchemy#86]
1. What version of Python are you using (`python --version`)?

Python3.6

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Linux-5.0.2-arch1-1-ARCH-x86_64-with-arch

3. What are the component versions in the environment (`pip list`)? 

```
snowflake-connector-python 1.6.10
snowflake-sqlalchemy       1.1.10
SQLAlchemy                 1.2.12
```

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

With `snowflake-sqlalchemy==1.1.10` it is impossible to create a Table with an index on any dialect.

5. What did you expect to see?

I would expect the snowflake dialect checks to be scoped to snowflake connections.

6. What did you see instead?

An error message is being thrown when creating a table with the `sqlite://` dialect: 
"Snowflake does not support indexes"

7. Can you set logging to DEBUG and collect the logs?

The problem is in base.py: it registers a global handler on the `before_create` event and throw an error without looking if the connection is using the `snowflake` dialect.

See https://github.com/snowflakedb/snowflake-sqlalchemy/blob/80191ba13bf7d0216e2d18225120803383034ed0/base.py#L411-420

```python
@sa_vnt.listens_for(Table, 'before_create')
def check_table(table, connection, **kw):
    # there should be a dialect check here
    if table.indexes:
        raise NotImplementedError("Snowflake does not support indexes")
```

**Comment by micaelbergeron** [comment]
@keller00 Can you please provide insights about why this has been closed? It doesn't seem to be fixed.

**Comment by keller00** [comment]
According to my testing this has fixed it:
https://github.com/snowflakedb/snowflake-sqlalchemy/blob/3741cd0363e1c08c0b5f73c8207e8be72a778f17/snowdialect.py#L567

**Comment by micaelbergeron** [comment]
Thanks @keller00 , for some reason I was looking at an old revision.
