### ISSUE TITLE
Passing session parameters to engine/session

### ISSUE THREAD

**Issue by villebro** [snowflakedb/snowflake-sqlalchemy#89]
Is there a way to pass session parameters to `snowflake-sqlalchemy`? Specifically I would like to override the account setting for `QUOTED_IDENTIFIERS_IGNORE_CASE`, but possibly other settings, too. I tried poking at the `URL`, `engine_params` and `metadata_params` but wasn't able to change the default settings. All help much appreciated.

**Comment by smtakeda** [comment]
Try `connect_args`:
```
engine = create_engine(URL(
    account='ACCOUNT',
...
    ),
    connect_args={
        'session_parameters': {'TIMEZONE': 'America/New_York',}
    },
    poolclass=NullPool,
    )

conn = engine.connect()
for rec in conn.execute("show parameters like 'TIMEZONE'"):
    print(rec)
conn.close()
engine.dispose()
```

**Comment by villebro** [comment]
Thanks for the quick help @smtakeda!
