### ISSUE TITLE
CopyInto's maxfilesize method expects a bool instead of an int

### ISSUE THREAD

**Issue by colemandsmith** [snowflakedb/snowflake-sqlalchemy#99]
Please answer these questions before submitting your issue. Thanks!

1. What version of Python are you using (`python --version`)?

Python 3.6.8 :: Anaconda, Inc.

2. What operating system and processor architecture are you using (`python -c 'import platform; print(platform.platform())'`)?

Darwin-18.5.0-x86_64-i386-64bit

3. What are the component versions in the environment (`pip list`)? 

snowflake-connector-python 1.7.11
snowflake-sqlalchemy 1.1.12

4. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

For a `CopyInto` object I made, I tried to set the maxfilesize to 50 MB (int value of 50000000) like so:

```
unload_stmt = CopyInto(table, bucket, formatter) 
unload_stmt.maxfilesize(50000000)
```

This was based on my understanding of the [snowflake docs](https://docs.snowflake.net/manuals/sql-reference/sql/copy-into-location.html#label-copy-into-location-copyoptions) that CSVs could be set to have a max file size in a `COPY INTO` statement.

5. What did you expect to see?

I expected to have the copy option set properly such that when this is compiled. `MAX_FILE_SIZE=50000000` appears in the generated SQL.

6. What did you see instead?

an error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-783ee63d0133> in <module>
----> 1 unload_stmt.maxfilesize(50000000)

~/miniconda3/envs/civis36/lib/python3.6/site-packages/snowflake/sqlalchemy/custom_commands.py in maxfilesize(self, max_size)
    118     def maxfilesize(self, max_size):
    119         if not isinstance(max_size, bool):
--> 120             raise TypeError("Parameter max_size should  be a boolean value")
    121         self.copy_options.update({'MAX_FILE_SIZE': translate_bool(max_size)})
    122 

TypeError: Parameter max_size should  be a boolean value
```

7. Can you set logging to DEBUG and collect the logs?

```
import logging
import os

for logger_name in ['snowflake.sqlalchemy', 'snowflake.connector', 'botocore']: 
    logger = logging.getLogger(logger_name)
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter('%(asctime)s - %(threadName)s %(filename)s:%(lineno)d - %(funcName)s() - %(levelname)s - %(message)s'))
    logger.addHandler(ch)
```
I believe this is unnecessary; see error.
______

The issue arises from [the maxfilesize method](https://github.com/snowflakedb/snowflake-sqlalchemy/blob/3741cd0363e1c08c0b5f73c8207e8be72a778f17/custom_commands.py#L118) on CopyInto. I believe this is a typo that may have arisen from going off the previous configs, which expect booleans.

**Comment by colemandsmith** [comment]
cc @smtakeda 
Hi, and sorry to bother, but right now we're at a bit of a roadblock on this and issue #97. I've made PRS #100 and #101  for this issue and the other, respectively, and would appreciate if someone from the dev team could take a look at these.
(the test runs for my PRs errored, but I'm not sure why - it looks unrelated to the code changes but rather related to some decryption process?)

**Comment by smtakeda** [comment]
@colemandsmith Let me try to get somebody on the issues.
